#!/usr/bin/env bash
# Display balances of all my major accounts. Budget and non-cash accounts are
# excluded.
source "$(dirname "$0")/common.sh"

required_var REGULAR_ASSET_ACCOUNTS
required_var REGULAR_LIABILITY_ACCOUNTS

b() {
    hledger bal --flat "$@"
}

echo ====== Assets =======
b -ERCP "$@" "${REGULAR_ASSET_ACCOUNTS[@]}"

echo

echo ==== Liabilities ====
b -EC "$@" "${REGULAR_LIABILITY_ACCOUNTS[@]}"
