#!/usr/bin/env bash
# Command to launch all banking sites and journals in one go.
source "$(dirname "$0")/common.sh"

required_var BANKING_SITES
required_var BANKING_BROWSER
required_var LEDGER_EDITOR

launch_browser() {
    if declare -f _launch_browser > /dev/null; then
        _launch_browser
    fi

    for site in "${BANKING_SITES[@]}"; do
        xdg-open "$site"
    done
}

launch_editor() {
    "${LEDGER_EDITOR[@]}" $(list_journals)
}

main() {
    if [[ "$#" -eq 0 ]]; then
        launch_browser "${BANKING_SITES[@]}"
        launch_editor
        return
    fi
    case "$1" in
        browser|chrome)
            launch_browser "${BANKING_SITES[@]}"
            ;;
        emacs|editor)
            launch_editor
            ;;
        *)
            fatal "unrecognized command: $1"
            ;;
    esac
}
is_main && main "$@"
