#!/usr/bin/env bash
# The incomestatement command shows Revenues vs Expenses to calculate cash net
# worth (excluding liabilities).

FROM="$(date -d "1 year ago" +"%Y-%m")"
TO="$(date -d "this month" +"%Y-%m")"


hledger is --monthly --tree --begin="$FROM" --end="$TO" --average --row-total "$@"
