#!/usr/bin/env bash
# Display balances of my accounts in the order that I check them,
# specified in the config.
source "$(dirname "$0")/common.sh"

required_var ACCOUNTS_IN_ORDER

b() {
    hledger bal --empty --no-total "$@"
}

for account in "${ACCOUNTS_IN_ORDER[@]}"; do
  b "$account"
done

