#!/usr/bin/env bash
# Display balances of all my major accounts. Budget and non-cash accounts are
# excluded.
source "$(dirname "$0")/common.sh"

required_var REGULAR_ASSET_ACCOUNTS

b() {
    hledger bal --flat "$@"
}

echo ====== Assets =======
b -ERCP "$@" "${REGULAR_ASSET_ACCOUNTS[@]}"

echo

if is_set REGULAR_LIABILITY_ACCOUNTS; then
    echo ==== Liabilities ====
    b -EC "$@" "${REGULAR_LIABILITY_ACCOUNTS[@]}"
fi
