#!/usr/bin/env bash
# Command to launch all banking sites and journals in one go.
source "$(dirname "$0")/common.sh"

required_var BANKING_SITES
required_var BANKING_BROWSER
required_var LEDGER_EDITOR

launch_browser() {
    "${BANKING_BROWSER[@]}" "${BANKING_SITES[@]}"
}

launch_editor() {
    "${LEDGER_EDITOR[@]}" $(list_journals)
}

main() {
    if [[ "$#" -eq 0 ]]; then
        launch_browser "${BANKING_SITES[@]}"
        launch_editor
        return
    fi
    case "$1" in
        browser|chrome)
            launch_browser "${BANKING_SITES[@]}"
            ;;
        emacs|editor)
            launch_editor
            ;;
        *)
            fatal "unrecognized command: $1"
            ;;
    esac
}
is_main && main "$@"