#!/usr/bin/env bash
# Report the last 12 months of expenses, broken down by expense account. Loans
# are included to account for total cashflow.
source "$(dirname "$0")/common.sh"

required_var EXPENSE_ACCOUNTS

FROM="$(date -d "1 year ago" +"%Y-%m")"
TO="$(date -d "next month" +"%Y-%m")"

hledger bal "${EXPENSE_ACCOUNTS[@]}" \
        --monthly \
        --tree \
        --no-elide \
        -b "$FROM" -e "$TO" \
        "$@"
