#!/usr/bin/env bash
# Display a summary of my spending for the current year, including this month.

: "${FROM=thisyear}"
: "${TO=nextmonth}"

hledger is --monthly --tree --begin="$FROM" --end="$TO" --average --row-total "$@"
