#!/usr/bin/env bash

# shellcheck source=common.sh
source "$(dirname "$0")/common.sh"

cd "$(dirname "$LEDGER_FILE")" || {
  fatal "couldn't navigate to LEDGER_FILE directory $LEDGER_FILE"
}

git "$@"
