#!/usr/bin/env bash
# The incomestatement command shows Revenues vs Expenses to calculate cash net
# worth (excluding liabilities).

: "${FROM=thisyear}"
: "${TO=nextmonth}"


hledger is --monthly --tree --begin="$FROM" --end="$TO" --average --row-total "$@"
