#!/usr/bin/env bash
# Utility for grepping journal files.

# shellcheck source=common.sh
source "$(dirname "${BASH_SOURCE[0]}")/common.sh"

# cd to the journals directory so that grep will list nice relative paths.
# Note that this requires GNU grep's default behavior for `--recursive` so this
# will break on macOS or other Unixes.
cd "$JOURNALS_DIR" && grep --recursive --ignore-case "$@"
