#!/usr/bin/env bash
# Make sure all journals have properly ordered transactions. This exists because
# hledger checks transaction dates globally, so it fails on my ledgers which are
# split into separate files by account.

# shellcheck source=common.sh
source "$(dirname "$0")/common.sh"

if hledger check ordereddates; then
  echo "No out-of-order transactions."
  exit 0
fi

fatal "Out-of-order transactions found!"
exit 1