#!/usr/bin/env bash
# Display balances of my envelope budgeting accounts.

# shellcheck source=common.sh
source "$(dirname "$0")/common.sh"

required_var BUDGET_ACCOUNTS

hledger bal \
        --auto \
        --cleared --pending \
        --row-total \
        --empty \
        --no-elide \
        --pretty-tables \
        --tree \
        "$@" \
        "${BUDGET_ACCOUNTS[@]}"
