#!/usr/bin/env bash
# Display balances of my accounts in the order that I check them,
# specified in the config.
# This is configured using a custom function check_accounts() which
# should invoke the cash and credit helper functions below depending
# on the account type.
source "$(dirname "$0")/common.sh"

required_func check_accounts

b() {
    hledger bal --empty --no-total "$@"
}

# Cash accounts (e.g. checkings and savings) reflect pending postings
# in their displayed total, but not unmarked ones (which denote
# transactions not yet received by the bank).
cash() {
  b --cleared --pending "$@"
}

# Credit accounts don't reflect pending postings, only cleared ones.
credit() {
  b --empty --cleared "$@"
}

check_accounts

